ARG NODEJS_VERSION="16"
FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-node:${NODEJS_VERSION}-run

WORKDIR /usr/src/app

# install node dependencies
COPY package.json  .
RUN JOBS=MAX npm install --unsafe-perm --production && npm cache clean --force

COPY . .

CMD ["npm", "start"]
